### ISSUE TITLE
服内可接收qq消息不可转发服内消息到qq

### ISSUE THREAD

**Issue by BaiRuoQiu** [ApliNi/Chat2QQ#26]
我这边出现如题所示的问题,望大佬给予分析以及勘误
**版本:**服务端 paper 1.19.4-550_miraimc 1.8-pre2_chat2qq1.8.6
**终端显示消息:**
[20:33:41 INFO]: BaiRuoQiu issued server command: /mirai login 323674454 QRCode ANDROID_WATCH
[20:33:41 INFO]: [MiraiMC] 登录新的机器人账号: 323674454, 协议: ANDROID_WATCH
[20:33:41 INFO]: [MiraiMC] Loaded account secrets from local cache.
[20:33:41 INFO]: [MiraiMC] ECDH key is valid.
[20:33:41 INFO]: [MiraiMC] Saved account secrets to local cache for fast login.
[20:33:41 INFO]: [MiraiMC] Login successful.
[20:33:41 INFO]: [MiraiMC] Server time updated, serverTime: 1686832421, diff: 0ms=0.0s
[20:33:41 INFO]: [MiraiMC] Syncing friend message history...
[20:33:41 INFO]: [MiraiMC] Start loading friend list...
[20:33:41 INFO]: [MiraiMC] Start loading stranger list...
[20:33:41 INFO]: [MiraiMC] Start loading friendGroup list...
[20:33:41 INFO]: [MiraiMC] Successfully loaded stranger list: 0 in total
[20:33:42 INFO]: [MiraiMC] Online OtherClients: OCE-AN10(MOBILE)
[20:33:42 INFO]: [MiraiMC] Start loading group list...
[20:33:42 INFO]: [MiraiMC] Syncing friend message history: Success.
[20:33:42 INFO]: [MiraiMC] Successfully loaded friendGroup list: 4 in total
[20:33:42 INFO]: [MiraiMC] Successfully loaded friend list: 2 in total
[20:33:42 INFO]: [MiraiMC] Successfully loaded group list: 1 in total.
[20:33:42 INFO]: [MiraiMC] Scheduled refresh login session in 19d 23h 55min 0.0s.
[20:33:42 INFO]: [MiraiMC] Scheduled key refresh in 23h 55min 0.0s.
[20:33:42 INFO]: [MiraiMC] Bot login successful.
[20:33:42 INFO]: [MiraiMC] BOT(323674454) 登录成功
[20:33:47 ERROR]: Could not pass event AsyncPlayerChatEvent to Chat2QQ v1.8.6
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at io.github.aplini.chat2qq.utils.Util.sendToGroup(Util.java:39) ~[Chat2QQ.jar:?]
at io.github.aplini.chat2qq.listener.onPlayerMessage.lambda$onPlayerChat$0(onPlayerMessage.java:55) ~[Chat2QQ.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at io.github.aplini.chat2qq.listener.onPlayerMessage.onPlayerChat(onPlayerMessage.java:55) ~[Chat2QQ.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor295.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2402) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2558) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2231) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:33:47 INFO]: [Not Secure] <BaiRuoQiu> w
[20:35:27 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.16.5 《简单》生存 大肠服务器(894845711)] 【技术部】 但是没有技术の白若秋(3245734064) -> 6
[20:36:02 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.16.5 《简单》生存 大肠服务器(894845711)] 【技术部】 但是没有技术の白若秋(3245734064) -> 又坏了
**详情描述:**
第一次安装时两边均正常使用,重启服务器后只能收不能发,删除MiraiMC以及chat2qq在plugin下文件夹后重新配置又恢复正常(检查过配置,未发现问题),但过了几分钟后重启服务器再次出现只收不发的现象,并且与重启前不同的是,服务器内消息发送出现几秒的延迟
**以下附上本人的
[config.txt](https://github.com/ApliNi/Chat2QQ/files/11757900/config.txt)
配置文件:**

**Comment by ApliNi** [comment]
我也遇到过这个问题, 这可能和Mirai或风控有关. 让账号在服务器上多登录一段时间就会自己恢复. 这是我无法解决的

**Comment by BaiRuoQiu** [comment]
了解啦,事实证明确实是这样的,今天恢复了一段时间,过一会又变成单向烟了,以下是报错
【睡觉部】 世界级乐山大佛-azhua8487(2181689629) -> 乐
[19:12:05 INFO]: §f[§7【睡觉部】 世界级乐山大佛-azhua8487§r§f] §7乐
[19:12:32 INFO]: [Not Secure] <azhua8487> 回复消息看不到啊
[19:12:34 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【睡觉部】 世界级乐山大佛-azhua8487(2181689629) -> [mirai:at:419819535]
[19:12:34 ERROR]: Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.8.6
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "io.github.aplini.chat2qq.Chat2QQ.group_cache_all" is null
at io.github.aplini.chat2qq.utils.Util.getNameFromCache(Util.java:46) ~[Chat2QQ.jar:?]
at io.github.aplini.chat2qq.utils.Util.formatQQID(Util.java:88) ~[Chat2QQ.jar:?]
at io.github.aplini.chat2qq.utils.renderGroupMessage.renderMessage1(renderGroupMessage.java:148) ~[Chat2QQ.jar:?]
at io.github.aplini.chat2qq.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:26) ~[Chat2QQ.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor298.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:121) ~[MiraiMC-Bukkit.jar:?]
at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:600) ~[MiraiMC-Bukkit.jar:?]
at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:600) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[MiraiMC-Bukkit.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[19:12:39 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【技术部】 国家级阴阳怪气-白若秋(3245734064) -> 你不会又忘记了服务器能直接发消息吧？
[19:12:39 INFO]: §f[§7【技术部】 国家级阴阳怪气-白若秋§r§f] §7你不会又忘记了服务器能直接发消息吧？
[19:12:43 INFO]: [Not Secure] <azhua8487> @也不行
[19:12:48 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【睡觉部】 世界级乐山大佛-azhua8487(2181689629) -> 你猜我为什么不在服务器里发
[19:12:48 INFO]: §f[§7【睡觉部】 世界级乐山大佛-azhua8487§r§f] §7你猜我为什么不在服务器里发
[19:13:12 ERROR]: Could not pass event MiraiMemberCardChangeEvent to Chat2QQ v1.8.6
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "io.github.aplini.chat2qq.Chat2QQ.group_cache_all" is null
at io.github.aplini.chat2qq.bot.onCardChange.onMiraiMemberCardChangeEvent(onCardChange.java:38) ~[Chat2QQ.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor297.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$44(MiraiEvent.java:170) ~[MiraiMC-Bukkit.jar:?]
at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:600) ~[MiraiMC-Bukkit.jar:?]
at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:600) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[MiraiMC-Bukkit.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[19:13:12 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【かめりあのdog】时不时用一下手机の屑ZhuXiu(419819535) -> 1.2秒延迟
[19:13:12 INFO]: §f[§7【かめりあのdog】时不时用一下手机の屑ZhuXiu§r§f] §71.2秒延迟
[19:13:12 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【睡觉部】 世界级乐山大佛-azhua8487(2181689629) -> 又是单向烟
[19:13:12 INFO]: §f[§7【睡觉部】 世界级乐山大佛-azhua8487§r§f] §7又是单向烟
[19:13:39 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【技术部】 国家级阴阳怪气-白若秋(3245734064) -> 这期间你做了什么吗？
[19:13:39 INFO]: §f[§7【技术部】 国家级阴阳怪气-白若秋§r§f] §7这期间你做了什么吗？
[19:13:44 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【技术部】 国家级阴阳怪气-白若秋(3245734064) -> 不然为啥又变成单向烟了？
[19:13:44 INFO]: §f[§7【技术部】 国家级阴阳怪气-白若秋§r§f] §7不然为啥又变成单向烟了？
[19:13:52 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【睡觉部】 世界级乐山大佛-azhua8487(2181689629) -> 没有吧
[19:13:52 INFO]: §f[§7【睡觉部】 世界级乐山大佛-azhua8487§r§f] §7没有吧
[19:13:58 INFO]: [MiraiMC] [GroupMessage/323674454] [MC Java 1.19.4 原版生电服(894845711)] 【睡觉部】 世界级乐山大佛-azhua8487(2181689629) -> zhuxiu给我发了个回复消息
[19:13:58 INFO]: §f[§7【睡觉部】 世界级乐山大佛-azhua8487§r§f] §7zhuxiu给我发了个回复消息
